###
get http://localhost:3003/api/users

###
get http://localhost:3003/api/users/63cca82a4b1875a5120c9955

###
get http://localhost:3003/api/users/63ccb56f4b1875a5120c9a02

###
post http://localhost:3003/api/users
content-type: application/json

{
    "username": "harry",
    "name": "harry potter",
    "password": "potter"
}

###
post http://localhost:3003/api/users
content-type: application/json

{
    "username": "megaman",
    "name": "robot guy",
    "password": "password"
}

###
put http://localhost:3003/api/blogs/63addb154b97b85a4094f45f
content-type: application/json

{
    "title": "Adventures of haha Forever",
    "author": "harry poooter",
    "url": "https://example.com",
    "likes": 5
}